### ISSUE TITLE
max research level is actually 20.

### ISSUE THREAD

**Issue by Lezus-Konrad** [cyclowns/blockstation13-master#10]
I did the same thing for it but just syndie shit and the max went to 20.

**Comment by mirrorcult** [comment]
do you actually unlock anything at 20 that you dont unlock at 10 though

**Comment by Lezus-Konrad** [comment]
welll. yeah.

**Comment by Lezus-Konrad** [comment]
we could add more RND shit like maybe have the instagib rifle at level 20.

**Comment by mirrorcult** [comment]
ill change it to 20 anyway might as well

**Comment by checkraisefold** [comment]
fixed meme smasher to give you level 20
